# Generated by Django 4.1.7 on 2023-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwork',
            name='post_disc',
            field=models.TextField(max_length=600),
        ),
    ]
