# Generated by Django 4.1.7 on 2023-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_postwork_post_disc'),
    ]

    operations = [
        migrations.CreateModel(
            name='carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/carausel')),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(max_length=600)),
            ],
        ),
    ]
